/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainApp;

import Account.SQLConnection;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kyanh
 */
public class TodolistJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TodolistJPanel
     */
    private String User;
    public TodolistJPanel(String user) {
        initComponents();
        setVisible(true);
        this.User = user;
        Date date = new Date();
        dcNgay.setDate(date);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String Ngay = sdf.format(dcNgay.getDate());
        TaoBang(Ngay);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTodolist = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbHoanThanh = new javax.swing.JTable();
        jcbHThanh = new javax.swing.JCheckBox();
        btnCapNhat = new javax.swing.JButton();
        tfItem = new javax.swing.JTextField();
        btnCapNhat1 = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        dcNgay = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(254, 244, 230));
        jPanel2.setPreferredSize(new java.awt.Dimension(789, 650));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách việc cần làm");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 95, 250, 25));

        jtbTodolist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbTodolist);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 125, 250, 300));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Danh sách việc đã hoàn thành");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 95, 250, 25));

        jtbHoanThanh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtbHoanThanh);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 125, 250, 300));

        jcbHThanh.setBackground(new java.awt.Color(254, 244, 230));
        jcbHThanh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcbHThanh.setText("Đã hoàn thành");
        jPanel2.add(jcbHThanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 450, 125, 25));

        btnCapNhat.setBackground(new java.awt.Color(58, 81, 153));
        btnCapNhat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.setBorder(null);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        jPanel2.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 450, 100, 25));

        tfItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tfItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(tfItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 425, 25));

        btnCapNhat1.setBackground(new java.awt.Color(58, 81, 153));
        btnCapNhat1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCapNhat1.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat1.setText("Xóa");
        btnCapNhat1.setBorder(null);
        btnCapNhat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhat1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCapNhat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 450, 100, 25));

        btnThem.setBackground(new java.awt.Color(58, 81, 153));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.setBorder(null);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel2.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 25, 100, 25));

        dcNgay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dcNgay.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcNgayPropertyChange(evt);
            }
        });
        jPanel2.add(dcNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 65, 350, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Ngày:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 65, 75, 25));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        if (jcbHThanh.isSelected() && (jtbTodolist.getSelectedRow() >= 0)){
            String TenCapNhat = listTenToDo.get(jtbTodolist.getSelectedRow());
            try{
                Connection conn = SQLConnection.getSQLConnection();
                String Sql = "update TODOLIST\n" +
                "set TRTHAI = ?\n" +
                "where MAND = ? AND TENTODO = ?";
                PreparedStatement ps = conn.prepareStatement(Sql);
                ps.setInt(1,1);
                ps.setString(2, this.User);
                ps.setString(3, TenCapNhat);
                ps.executeUpdate();
            }
            catch(Exception e){
            }
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String Ngay = sdf.format(dcNgay.getDate());
            TaoBang(Ngay);
            jcbHThanh.setSelected(false);
        }
        else {
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnCapNhat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhat1ActionPerformed

        if (jtbHoanThanh.getSelectedRow() >= 0){
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String Ngay = sdf.format(dcNgay.getDate());
            String TenXoa = listTenHThanh.get(jtbHoanThanh.getSelectedRow());
            try{
                Connection conn = SQLConnection.getSQLConnection();
                String Sql = "delete from TODOLIST\n" +
                "where MAND = ? AND TENTODO = ? AND NGAYTODO = ?";
                PreparedStatement ps = conn.prepareStatement(Sql);
                ps.setString(1, this.User);
                ps.setString(2, TenXoa);
                ps.setString(3, Ngay);
                ps.executeUpdate();
            }
            catch(Exception e){
                System.out.print(e);
            }
            TaoBang(Ngay);
        }
        else {
        }
    }//GEN-LAST:event_btnCapNhat1ActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String tenToDo = tfItem.getText();
        if (!tenToDo.isEmpty()){
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String Ngay = sdf.format(dcNgay.getDate());
            try{
                Connection con = SQLConnection.getSQLConnection();
                String SQL = "INSERT INTO TODOLIST(MAND,TENTODO,NGAYTODO,TRTHAI) VALUES (?,?,?,0) ";
                PreparedStatement ps = con.prepareStatement(SQL);
                ps.setString(1,this.User);
                ps.setString(2,tenToDo);
                ps.setString(3,Ngay);
                ps.executeUpdate();
            }catch (Exception e){
                System.out.print("Lỗi thêm todo" + e);
            }
            TaoBang(Ngay);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void dcNgayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcNgayPropertyChange
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String Ngay = sdf.format(dcNgay.getDate());
        TaoBang(Ngay);
    }//GEN-LAST:event_dcNgayPropertyChange

    ArrayList <String> listTenToDo = new ArrayList <String> () ;
    ArrayList <String> listTenHThanh= new ArrayList <String> () ;

    int MaTodo;
    DefaultTableModel dtmTDL;
    DefaultTableModel dtmHThanh;

    
    public void TaoBang(String Ngay){
        listTenToDo.clear();
        listTenHThanh.clear();
        dtmTDL = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
           return false;
        }};
        dtmHThanh = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
           return false;
        }};
        String TieuDe1[] ={"Việc cần làm"}; 
        dtmTDL.setColumnIdentifiers(TieuDe1);
        jtbTodolist.setModel(dtmTDL);
        String TieuDe2[] ={"Việc đã hoàn thành"}; 
        dtmHThanh.setColumnIdentifiers(TieuDe2);
        jtbHoanThanh.setModel(dtmHThanh);
        setVisible(true);
        TaoTodoList(Ngay);
    }
    
    public void TaoTodoList(String Ngay){
        try{
            Connection conn = SQLConnection.getSQLConnection();
            ResultSet rs;
            String sql = "Select TENTODO, TRTHAI FROM TODOLIST WHERE MAND = ? AND NGAYTODO = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1,this.User);
            ps.setString(2,Ngay);
            rs = ps.executeQuery();
            while(rs.next())
            {
                if ("0".equals(rs.getString("TRTHAI"))){
                    listTenToDo.add(rs.getString(1));
                    dtmTDL.addRow(new String [] {rs.getString(1)});
                }
                else{
                    listTenHThanh.add(rs.getString(1));
                    dtmHThanh.addRow(new String [] {rs.getString(1)});
                }
            }
        }
        
        catch(Exception e) 
        {
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnCapNhat1;
    private javax.swing.JButton btnThem;
    private com.toedter.calendar.JDateChooser dcNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox jcbHThanh;
    private javax.swing.JTable jtbHoanThanh;
    private javax.swing.JTable jtbTodolist;
    private javax.swing.JTextField tfItem;
    // End of variables declaration//GEN-END:variables
}
