/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Account;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author kyanh
 */
public class XacThucTaiKhoan extends javax.swing.JFrame {

    /**
     * Creates new form DoiMatKhau
     */
    public XacThucTaiKhoan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbEmail = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lbNoti = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(254, 244, 230));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(60, 47, 37));
        lbEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbEmail.setText("Email:");
        jPanel2.add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 75, 75, 25));

        inputEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inputEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 75, 375, 25));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(58, 81, 153));
        btnBack.setText("Quay lại");
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 125, 150, 35));

        btnNext.setBackground(new java.awt.Color(58, 81, 153));
        btnNext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Tiếp tục");
        btnNext.setBorder(null);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel2.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 125, 150, 35));

        lbNoti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbNoti.setText("Vui lòng nhập email mà bạn dùng để đăng ký tài khoản");
        jPanel2.add(lbNoti, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 450, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, 500, 175));

        jPanel1.setBackground(new java.awt.Color(58, 81, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setBackground(new java.awt.Color(60, 47, 37));
        lbTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTitle.setText("XÁC THỰC TÀI KHOẢN");
        jPanel1.add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 13, 400, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 250));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DangNhap().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private String getUser(String mail)
    {
        try{ 
            Connection con = SQLConnection.getSQLConnection();
            String SQL = "SELECT MAND FROM NGUOIDUNG WHERE EMAIL=?";
            PreparedStatement ps = con.prepareStatement(SQL); 
            ps.setString(1, mail); 
            ResultSet rs = ps.executeQuery(); 
            String ten = null;
            while (rs.next())
                ten = rs.getString(1);
            return ten;
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Lấy mã người dùng không thành công \n"+e, "Lỗi không xác định", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
    
    public Boolean setCodetoSQL(String user, String code)
    {
        String encryptedCode = new SHA256().encryptThisString(code);
        try{ 
            Connection con = SQLConnection.getSQLConnection();
            String SQL = "UPDATE XACNHAN SET XACNHAN = ? WHERE MAND=?";
            PreparedStatement ps = con.prepareStatement(SQL); 
            ps.setString(1, encryptedCode); 
            ps.setString(2, user); 
            int kq = ps.executeUpdate(); 
            
            if (kq == 0) //Không có người dùng nào tên user
            {
                try{
                    String SQL1 = "INSERT INTO XACNHAN(MAND,XACNHAN) VALUES(?,?)";
                    PreparedStatement ps1 = con.prepareStatement(SQL1); 
                    ps1.setString(1, user); 
                    ps1.setString(2, encryptedCode); 
                    ps1.executeUpdate(); 
                }catch (Exception ex){
                    JOptionPane.showMessageDialog(this, "Không thể thêm mã xác nhận vào cơ sở dữ liệu "+ex, "Lỗi không xác định", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            }
            return true;
        }catch (Exception ex){
            JOptionPane.showMessageDialog(this, "Không thể cập nhật mã xác nhận mới vào cơ sở dữ liệu "+ex, "Lỗi không xác định", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
    }
    
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (inputEmail.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Chưa nhập email", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String user = getUser(inputEmail.getText());
            if (user != null)
            {
                String code = new RandomString().getRandomString();
                try{
                    new Mail().SendMailto(inputEmail.getText(), code);
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(this, ex, "Lỗi gửi email", JOptionPane.ERROR_MESSAGE);
                }
                
                //System.out.print("thêm code vô csdl ");
                if (setCodetoSQL(user,code) == true){
                    JOptionPane.showMessageDialog(this, "Gửi email xác nhận thành công!");
                    this.dispose();
                    new XacNhan(user).setVisible(true);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Email không tồn tại trong cơ sở dữ liệu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbNoti;
    private javax.swing.JLabel lbTitle;
    // End of variables declaration//GEN-END:variables
}
